### ISSUE TITLE
How to run your own banks?

### ISSUE THREAD

**Issue by TawsTm** [Granjow/fmod-service-api#1]
Hello @Granjow,

i am able to run the demo file when executing the demo-player. I would like to know what your intended workflow for using other banks would look like. The generated code files and the FmodSampleProject are a bit confusing to me. What exactly am i supposed to generate myself and which of these files are more or less unimportant if i am playing a simple bank?

Thanks in advance!

**Comment by Granjow** [comment]
Hi @TawsTm , you can either use the player functionality directly if you want to load banks and play events by their ID, or (which is how I use it) generate a player with the codegen which is tailored for your project and provides full typing support.

If you take the second approach, you first have to describe your project and then you generate it. Then you only use the generated player. So:

1. Generate your project player with `IFmodProject` data. Here you define in which banks your events are. If all are in Master, fine too :) The player uses this information to decide whether a bank needs to be loaded.
2. For playback, use the generated player and enjoy IDE/typing support.

Does that help or is your question going into another direction?

**Comment by TawsTm** [comment]
Thank you @Granjow! It took me a while to understand the general logic and your style to organize things, but i got most of it working for now. Great job with the example.
